### ISSUE TITLE
[All browsers/devices] It is possible to go to step 2 without email address. No validation of field

### ISSUE THREAD

**Issue by qatestlab** [paleohacks123/qa-paleorecipeteam-sweets-t1#1]
1. Open the site https://www.paleorecipeteam.com/sweets-stage/
2. Scroll page down to the "Ship Me The Book" button
3. Click the "Ship Me The Book" button
4. Click the "Go To Step 2" button

Actual result: It is possible to go to step 2 without entering email address
Expected result: Warning message should appears

**Comment by qatestlab** [comment]
![2018-03-14_1837](https://user-images.githubusercontent.com/37377592/37416585-cbc860d4-27b6-11e8-9108-edf84c00d8bf.png)

**Comment by paleohacks123** [comment]
This is as desired. We want people to be able to go on to the next page if they opt out of giving us their email
