### ISSUE TITLE
[All browsers/devices] Pictures and icons are pixelated on the page

### ISSUE THREAD

**Issue by qatestlab** [paleohacks123/qa-paleorecipeteam-sweets-t1#10]
1. Open the site https://www.paleorecipeteam.com/sweets-stage/ 
2. Pay attention to the icons displaying on the page
3. Scroll down the page
4. Look at pictures displaying

Actual result: Pictures and icons are pixelated on the page
Expected result: Pictures and icons are sharp-displayed
![screenshot_20180315-103235](https://user-images.githubusercontent.com/37377592/37455953-fb19948a-2846-11e8-8a0b-58f173aca57b.png)
![screenshot_20180315-103522](https://user-images.githubusercontent.com/37377592/37455967-02906770-2847-11e8-8d66-64e4f668ddcb.png)

**Comment by paleohacks123** [comment]
We fixed the phone icon but the rest are not that bad - we've highly compressed our images to help combat a large file size & page load
