### ISSUE TITLE
[All browsers, Mobile, Tablet] PageSpeed Insigh. Unavailable speed medium optimization

### ISSUE THREAD

**Issue by qatestlab** [paleohacks123/qa-paleorecipeteam-sweets-t1#9]
1. Log in to the site https://developers.google.com
2. Select "PageSpeed Insights" tool
3. Type URL of the site 
4. Click the "Analyze"

Actual result: Unavailable speed medium optimization as the result
Expected result: Available speed and good optimization is displayed

![2018-03-15_1130](https://user-images.githubusercontent.com/37377592/37455355-8831fa80-2845-11e8-8ecf-1a2718d9d424.png)

**Comment by paleohacks123** [comment]
You can use google chromes inspect tool to get speed insights. This is because we've set google not to crawl our stage environment.
